# Generated by Django 2.1.7 on 2020-04-28 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('agent_name', models.CharField(default='', max_length=50, verbose_name='agent_name')),
                ('direction', models.CharField(default='callin', max_length=20, verbose_name='direction')),
                ('other_number', models.CharField(default='', max_length=50, verbose_name='other_number')),
                ('uuid', models.UUIDField(verbose_name='uuid')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_datetime')),
                ('answered_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='answered_datetime')),
                ('hangup_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='hangup_datetime')),
                ('bleg_uuid', models.UUIDField(blank=True, default=None, null=True, verbose_name='bleg_uuid')),
                ('hangup_cause', models.CharField(default='', max_length=50, verbose_name='hangup_cause')),
                ('toltal_timed', models.CharField(default='', max_length=20, verbose_name='toltal_timed')),
                ('talk_timed', models.CharField(default='', max_length=20, verbose_name='talk_timed')),
                ('calling_ip', models.CharField(default='', max_length=20, verbose_name='calling_ip')),
                ('called_ip', models.CharField(default='', max_length=20, verbose_name='called_ip')),
            ],
            options={
                'db_table': 'zswitch_cc_agent_cdr',
            },
        ),
    ]
