# Generated by Django 2.1.7 on 2019-12-12 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('userid', models.SmallIntegerField(default=-1, verbose_name='userid')),
                ('queue', models.CharField(blank=True, default='', max_length=100, verbose_name='queue')),
                ('agent_name', models.CharField(default='', max_length=50, verbose_name='agent_name')),
                ('dir', models.CharField(default='callin', max_length=20, verbose_name='dir')),
                ('other_number', models.CharField(default='', max_length=50, verbose_name='other_number')),
                ('other_area_code', models.CharField(blank=True, default='', max_length=20, verbose_name='other_area_code')),
                ('uuid', models.UUIDField(verbose_name='uuid')),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='source')),
                ('context', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='context')),
                ('channel_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='channel_name')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_datetime')),
                ('answered_datatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='answered_datetime')),
                ('hangup_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='hangup_datetime')),
                ('bleg_uuid', models.UUIDField(blank=True, default=None, null=True, verbose_name='bleg_uuid')),
                ('hangup_cause', models.CharField(default='', max_length=50, verbose_name='hangup_cause')),
                ('toltal_timed', models.CharField(default='', max_length=20, verbose_name='toltal_timed')),
                ('talk_timed', models.CharField(default='', max_length=20, verbose_name='talk_timed')),
            ],
            options={
                'db_table': 'zswitch_cc_agent_cdr',
            },
        ),
    ]
